### ISSUE TITLE
Redmine 3 compatibility

### ISSUE THREAD

**Issue by kostajh** [gongo/org-redmine#10]
Curious if anyone has tested this with Redmine 3.x

**Comment by kostajh** [comment]
So, I've tested with Redmine 3.0.x. It appears to sort of work... I can view some issues (not all), and inserting a subtree into an org doc only loads some of the information:

```
* #249 Add RSS icon to homepage :Feature:
  :PROPERTIES:
  :issue_id: 249
  :updated_on: 2015-08-24T16:52:37Z
  :END:
```
This is missing the description, start date, etc.

**Comment by gongo** [comment]
Sorry for reply late. I'll survey this issue.

**Comment by gongo** [comment]
@kostajh I could get issue with "description" property on Redmine 3.

e.g.

```lisp
(setq org-redmine-uri "https://bugs.ruby-lang.org") ;; work Redmine 3.1
(setq org-redmine-auth-api-key nil)
(setq org-redmine-template-property
      '(("descripton" . "%d%")
        ("status"     . "%s_n%")))
```

And `M-x org-redmine-get-issue RET 11473`, then:

![2015-09-03 9 44 46](https://cloud.githubusercontent.com/assets/124713/9648177/7a679872-5220-11e5-8da8-8f4daa3916c5.png)

**Comment by kostajh** [comment]
Ah, you are right. I see that is working now. Thanks!

Wataru MIYAGUNI writes:

> @kostajh I could get issue with "description" property on Redmine 3.
>
> e.g.
>
> ```lisp
> (setq org-redmine-uri "https://bugs.ruby-lang.org") ;; work Redmine 3.1
> (setq org-redmine-auth-api-key nil)
> (setq org-redmine-template-property
>       '(("descripton" . "%d%")
>         ("status"     . "%s_n%")))
> ```
>
> And `M-x org-redmine-get-issue RET 11473`, then:
>
> ![2015-09-03 9 44 46](https://cloud.githubusercontent.com/assets/124713/9648177/7a679872-5220-11e5-8da8-8f4daa3916c5.png)
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gongo/org-redmine/issues/10#issuecomment-137283378

-- 
kosta@kostaharlan.net

**Comment by gongo** [comment]
:smile:
