### ISSUE TITLE
Instructions on use inside orgmode?

### ISSUE THREAD

**Issue by marxistvegan** [gongo/org-redmine#14]
Hey folks, I am a bit new to orgmode, but wondering if there are some instructions on using this inside orgmode?

**Comment by gongo** [comment]
Hi @marxistvegan 

- `M-x org-redmine-anything-show-issue-all`

    Display recent issues using `anything`

- `C-u M-x org-redmine-anything-show-issue-all`

    Display recent issues that assigned me using `anything`

- `M-x org-redmine-get-issue`

    Fetch specified issue and insert to org-mode tree

Thanks.
