### ISSUE TITLE
Invalid function: helm-build-sync-source

### ISSUE THREAD

**Issue by MaksVal** [gongo/org-redmine#25]
Hi!
I'm getting this error when using the function: org-redmine-helm-show-issue-all:
org-redmine-helm-show-issue-all: Invalid function: helm-build-sync-source

Do you can help me?

GNU Emacs 24.5.1
ORG-REDMINE:
 ;; Package-Version: 20160205.344
 ;; Keywords: redmine org
 ;; Version: 0.1.0
Thanks!

**Comment by syohex** [comment]
Did you use latest helm ? If you use old helm, please upgrade helm version and try again.

**Comment by joaoalf** [comment]
Hello @syohex 

I'm getting this error also.

org-redmine: 20160205.344
helm-core: 20160701.2319

**Comment by gongo** [comment]
Fixed at GH-26
