### ISSUE TITLE
Use helm instead of anything

### ISSUE THREAD

**Issue by gongo** [gongo/org-redmine#9]

**Comment by zakame** [comment]
Its is useable on Helm as is, save for the lack of shortcuts on the actions (Open Browser/Insert Subtree.)

**Comment by kostajh** [comment]
@zakame how are you using this with helm? There's no helm in the codebase as far as I can see.

**Comment by gongo** [comment]
https://github.com/gongo/org-redmine/pull/23#issuecomment-180163505

**Comment by zakame** [comment]
Thanks @gongo ! :+1: 

@kostajh I just installed it back then, but didn't notice until now that it pulled in Anything.el :D
